spring.application.name=Employee
# Database URL (replace 'mydb' with your database name)
spring.datasource.url=jdbc:mysql://localhost:3306/Patient

# Database credentials
spring.datasource.username=root
spring.datasource.password=root
without.restart=naben

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect (Important for proper SQL generation)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
